services:
  sui:
    image: alireza7/s-ui
    container_name: sui
    volumes:
      - ./db:/app/db
      - ../nginx/certs:/app/cert
    tty: true
    restart: unless-stopped
    entrypoint: "./entrypoint.sh"
    networks:
      - nginx_net

networks:
  nginx_net:
    external: true

# Panel Port: 2095
# Panel Path: /app/
# Subscription Port: 2096
# Subscription Path: /sub/
# User/Password: admin
